### ISSUE TITLE
Register ne fonctionne pas lorsqu'on est sur le VPN de l'école

### ISSUE THREAD

**Issue by fuhrmanator** [louis-antoine-etsmtl/ETS-PFE042-EvalueTonSavoir-Frontend#30]
**Describe the bug**
When connected to the server via VPN (ETS) and trying to Register, nothing happens after clicking the Register button.

Looking at the developer console, I see:

```
13:06:36.173 10.196.10.69:4400/user/register:1 
        
        
       Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
```

**To Reproduce**
1. Connect to the ETS network via VPN.
2. Click on Register
3. Enter email and password
4. Click the Register button
5. Observe that nothing happens.

**Expected behavior**
Takes me to the register screen...

**Screenshots**
![image](https://github.com/louis-antoine-etsmtl/ETS-PFE042-EvalueTonSavoir-Frontend/assets/7606540/23fd7d98-eda2-4dd9-bbac-97a224e1a15a)

It's my guess that the URL 10.196.10.69:4400/user/register is not visible on the VPN, because it's missing a host name.

**Comment by louis-antoine-etsmtl** [comment]
Closing this issue as it appears the server crashed during the registration process. A feedback mechanism has been implemented to address such errors in the future.
