### ISSUE TITLE
"Veuillez choisir un dossier" error is coming too late

### ISSUE THREAD

**Issue by fuhrmanator** [louis-antoine-etsmtl/ETS-PFE042-EvalueTonSavoir-Frontend#32]
**Describe the bug**
When I try to save a quiz, if I didn't select a folder, I get an error (after I've named the quiz). Because this error comes "late" I have to cancel the dialog to go back to select the folder. 

**To Reproduce**
1. Create a quiz
2. "Enregistrer" button
3. Enter a name
4. See the pop-up error (alert).
5. Click OK
6. Click Annuler
7. (Lose the name of the quiz)
8. Select "default" folder
9. click "Enregistrer"
10. Retype the name of the quiz
 
**Expected behavior**
I want an interface that is intuitive - either the button "enregistrer" is inactive until I select a folder, or the folder selection is part of the name dialog, etc.

**Screenshots**
![image](https://github.com/louis-antoine-etsmtl/ETS-PFE042-EvalueTonSavoir-Frontend/assets/7606540/002f3d84-8b7c-41bb-b529-1a8776106b52)

**Comment by louis-antoine-etsmtl** [comment]
Issue resolved with implementation of the new user interface.
