### ISSUE TITLE
Can't see added quiz (it's not intuitive that I must select a "default" folder to see a quiz I added)

### ISSUE THREAD

**Issue by fuhrmanator** [louis-antoine-etsmtl/ETS-PFE042-EvalueTonSavoir-Frontend#33]
**Describe the bug**
I created and named a quiz in default folder, but it doesn't show up on "Tableau de bord" (default folder is not selected). This is a bug, because "default" implies you don't need to do anything.

**To Reproduce**
1. Create a quiz
2. Choose "default" folder
3. Enregistrer
4. Observe no quiz added in the "Tableau de bord" screen
5. Workaround is to choose the default folder.
6. Strangely, it's not possible to  "deselect" this (and return the menu to the "Select a folder" state.

**Expected behavior**
Expect to see the quiz I added in a list. Perhaps "default" should be set by default.

**Screenshots**

After adding a quiz, nothing is visible:
![image](https://github.com/louis-antoine-etsmtl/ETS-PFE042-EvalueTonSavoir-Frontend/assets/7606540/52acc288-3dd8-45ba-89da-f06a6cc7cda1)

After selecting default folder, I see it:
![image](https://github.com/louis-antoine-etsmtl/ETS-PFE042-EvalueTonSavoir-Frontend/assets/7606540/44ff75a5-af81-4e44-892c-d7128b208d02)

After going back to the page, it's invisible again (default is deselected):
![image](https://github.com/louis-antoine-etsmtl/ETS-PFE042-EvalueTonSavoir-Frontend/assets/7606540/7669678b-93a4-4031-bb23-23e5cd8f760c)

**Comment by louis-antoine-etsmtl** [comment]
Issue fixed with nes UI

**Comment by louis-antoine-etsmtl** [comment]
Issue resolved with implementation of the new user interface.
