### ISSUE TITLE
Choix de vrai/faux ont T ou F (de l'anglais)

### ISSUE THREAD

**Issue by fuhrmanator** [louis-antoine-etsmtl/ETS-PFE042-EvalueTonSavoir-Frontend#36]
**Describe the bug**
Dans l'interface étudiant, on voit (T) et (F) au lieu de (V) ou (F)

**To Reproduce**
1. Connecter un étudiant à un quiz avec une question v/f.
2. Observer les lettres (T)  et (F).

**Expected behavior**
(V) ou (F) pour les termes en français.

**Screenshots**
![image](https://github.com/louis-antoine-etsmtl/ETS-PFE042-EvalueTonSavoir-Frontend/assets/7606540/01aab575-4c0a-44fa-ae56-39520a32b70b)

**Comment by louis-antoine-etsmtl** [comment]
Kamino closed and cloned this issue to [louis-antoine-etsmtl/EvalueTonSavoir](https://github.com/louis-antoine-etsmtl/EvalueTonSavoir/issues/25)
